# Generated by Django 5.1.2 on 2024-11-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livros_data_emprestado_alter_livros_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
