# Generated by Django 5.1.2 on 2024-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_categoria_livros_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='genero',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
