# Generated by Django 5.1.2 on 2024-11-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_alter_livros_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='livros.categoria'),
        ),
    ]
