# Generated by Django 5.1.2 on 2024-11-04 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_alter_livros_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
