# Generated by Django 5.1.2 on 2024-11-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='genero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
