# Generated by Django 5.1.2 on 2024-11-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_alter_livros_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
