# Generated by Django 5.1.2 on 2024-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_alter_livros_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano_publicacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
