# Generated by Django 5.1.2 on 2024-11-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_alter_livros_ano_publicacao_alter_livros_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano_publicacao',
            field=models.CharField(max_length=15),
        ),
    ]
