# Generated by Django 5.1.2 on 2024-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_remove_livros_quantidade_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='quantidade_total',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='genero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='livros',
            name='quantidade_disponivel',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
