# Generated by Django 5.1.2 on 2024-11-05 19:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0014_livros_quantidade_total_alter_livros_genero_and_more'),
        ('usuarios', '0004_alter_usuario_endereco_alter_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data_emprestado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='nome_emprestado',
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestado', models.CharField(blank=True, max_length=100, null=True)),
                ('data_emprestado', models.DateField(default=datetime.date.today, null=True)),
                ('data_devolucao', models.DateField(blank=True, max_length=100, null=True)),
                ('tempo_duracao', models.DateField(blank=True, max_length=100, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
        ),
    ]
