# Generated by Django 5.1.2 on 2024-11-05 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0016_alter_emprestimo_livro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 18, 24, 15, 570152)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='tempo_duracao',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
