# Generated by Django 5.1.2 on 2024-11-05 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0017_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='tempo_duracao',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
