# Generated by Django 5.1.2 on 2024-11-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(blank=True, choices=[('adm', 'Administrador'), ('lei', 'Leitor')], max_length=3, null=True),
        ),
    ]
