# Generated by Django 5.1.2 on 2024-11-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_tipo_usuario_usuario_tipo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_user',
            new_name='tipo_usuario',
        ),
    ]
